[Feat] 헬스 체크 코드 추가

diff --git a/cicd/jenkins/backend/Jenkinsfile b/cicd/jenkins/backend/Jenkinsfile
--- a/cicd/jenkins/backend/Jenkinsfile
+++ b/cicd/jenkins/backend/Jenkinsfile
@@ -100,6 +100,25 @@ pipeline {
                                             kubectl apply -f backend-deployment.yml
                                             kubectl apply -f backend-svc.yml
                                             kubectl apply -f backend-ingress.yml
+
+                                            sleep 20
+
+                                            check_health() {
+                                                for i in {1..12}; do
+                                                    HTTP_STATUS=$(curl -s -o /dev/null -w "%{http_code}" -H "canary-version: new" http://192.0.30.101/test)
+                                                    echo ${HTTP_STATUS}
+                                                    if [ "$HTTP_STATUS" != "200" ]; then
+                                                        echo "Error: Service did not return 200 status. Exiting..."
+                                                        exit 1
+                                                    fi
+                                                    sleep 1
+                                                done
+                                            }
+
+                                            # 10% 트래픽에 대해 헬스 체크
+                                            check_health
+
+
                                         '''
                                     )
                                 ]
